import Head from "next/head";
import { CheckIcon } from "@heroicons/react/outline";

import { MainLayout } from "../components/layout";

const todos = [
  {
    name: "Introduction",
    description: "Your task is to implement a simple single-user blogging engine frontend in React",
  },
  {
    name: "Goal",
    description:
      "The goal here is not just to see if you can do an app, but how you do it. So please write it as if it were a big production app, that includes code structure, validations, usage of git, documentation, tests, linting, etc.",
  },
  {
    name: "Tip",
    description:
      "We realize that some subtasks can be very time consuming, if you just don't have the time, you can write short text description of how would you solve the problem",
  },
  {
    name: "Common",
    description: "We use Swagger/OpenAPI for API documentation",
  },
  {
    name: "API",
    description: "Check out the API here https://github.com/Applifting/fullstack-exercise/blob/master/api.yml",
  },
  {
    name: "Wireframes",
    description:
      "Implement the wireframes here https://www.figma.com/file/VagZOrr3TjTAxGCpCUTSrO/Applifting-%7C-Full-Stack-Cvi%C4%8Den%C3%AD?node-id=2%3A2",
  },
];

const Home = () => {
  return (
    <div className="bg-white">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="px-4 py-16 mx-auto sm:px-6 lg:px-8 max-w-7xl">
        <div className="max-w-3xl mx-auto text-center">
          <h2 className="text-3xl font-extrabold text-gray-900">Blogging engine</h2>
          <p className="mt-4 text-lg text-gray-500">
            Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ipsa libero labore natus atque, ducimus sed.
          </p>
        </div>
        <dl className="grid grid-cols-1 mt-12 space-y-10 sm:space-y-0 sm:gap-x-6 sm:gap-y-12 lg:gap-x-8">
          {todos.map((feature) => (
            <div key={feature.name} className="relative">
              <dt>
                <CheckIcon className="absolute w-6 h-6 text-green-500" aria-hidden="true" />
                <p className="text-lg font-medium leading-6 text-gray-900 ml-9">{feature.name}</p>
              </dt>
              <dd className="mt-2 text-base text-gray-500 ml-9">{feature.description}</dd>
            </div>
          ))}
        </dl>
      </div>
    </div>
  );
};

Home.getLayout = (page) => {
  return <MainLayout>{page}</MainLayout>;
};

export default Home;
