import Head from "next/head";

import { MainLayout } from "../components/layout";
import { AuthProvider } from "../modules/auth";

const Home = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AuthProvider>Signed in</AuthProvider>
    </div>
  );
};

Home.getLayout = (page) => {
  return <MainLayout>{page}</MainLayout>;
};

export default Home;
